import mongoose from "mongoose"
const slotSchema=new mongoose.Schema(
    {
        turfId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Turf",
            required:true,
        },
        start:{
            type:Date,
            required:true,
        },
        end:{
            type:Date,
            required:true,
        },
        isBooked:{
            type:Boolean,
            default:true,
        },
        matchId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Match",
            default:null,
        },
        bookingId:{
            type:mongoose.Schema.Types.ObjectId,
        }
    }
)